//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.1.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Core.WebDriverFactories.ExtendedChromeDriverFactory")]
        public string ChromeFactory {
            get {
                return ((string)(this["ChromeFactory"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Core.WebDriverFactories.ExtendedIeDriverFactory")]
        public string IeFactory {
            get {
                return ((string)(this["IeFactory"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Core.WebDriverFactories.ExtendedEdgeDriverFactory")]
        public string EdgeFactory {
            get {
                return ((string)(this["EdgeFactory"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Core.WebDriverFactories.ExtendedFireFoxDriverFactory")]
        public string FireFoxFactory {
            get {
                return ((string)(this["FireFoxFactory"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Chunlong")]
        public string EmailFromName {
            get {
                return ((string)(this["EmailFromName"]));
            }
            set {
                this["EmailFromName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("57795973@qq.com")]
        public string EmailFromEmailAddress {
            get {
                return ((string)(this["EmailFromEmailAddress"]));
            }
            set {
                this["EmailFromEmailAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SharePointer")]
        public string EmailToName {
            get {
                return ((string)(this["EmailToName"]));
            }
            set {
                this["EmailToName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("chunlonl@microsoft.com")]
        public string EmailToEmailAddress {
            get {
                return ((string)(this["EmailToEmailAddress"]));
            }
            set {
                this["EmailToEmailAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Chunlong")]
        public string EmailCcName {
            get {
                return ((string)(this["EmailCcName"]));
            }
            set {
                this["EmailCcName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("57795973@qq.com")]
        public string EmailCcEmailAddress {
            get {
                return ((string)(this["EmailCcEmailAddress"]));
            }
            set {
                this["EmailCcEmailAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Slow performance was detected")]
        public string EmailSubject {
            get {
                return ((string)(this["EmailSubject"]));
            }
            set {
                this["EmailSubject"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Slow performance was detected just now, pls check PageLoadMetricsCsv and log file" +
            " for more details. ")]
        public string EmailBody {
            get {
                return ((string)(this["EmailBody"]));
            }
            set {
                this["EmailBody"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("smtp.qq.com")]
        public string EmailSmtpAddress {
            get {
                return ((string)(this["EmailSmtpAddress"]));
            }
            set {
                this["EmailSmtpAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("465")]
        public int EmailSmtpPort {
            get {
                return ((int)(this["EmailSmtpPort"]));
            }
            set {
                this["EmailSmtpPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("57795973")]
        public string EmailSenderLoginName {
            get {
                return ((string)(this["EmailSenderLoginName"]));
            }
            set {
                this["EmailSenderLoginName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ljdrkepotropbieg")]
        public string EmailSenderLoginPasswords {
            get {
                return ((string)(this["EmailSenderLoginPasswords"]));
            }
            set {
                this["EmailSenderLoginPasswords"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EmailIsSenderLoginPasswordsEncrypted {
            get {
                return ((bool)(this["EmailIsSenderLoginPasswordsEncrypted"]));
            }
            set {
                this["EmailIsSenderLoginPasswordsEncrypted"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".\\Logs\\PageLoadMetricsCsv.csv")]
        public string PageLoadMetricsCsv {
            get {
                return ((string)(this["PageLoadMetricsCsv"]));
            }
            set {
                this["PageLoadMetricsCsv"] = value;
            }
        }
    }
}
